### ISSUE TITLE
"graphviz" dependency appears to be specified incorrectly

### ISSUE THREAD

**Issue by ceball** [timkpaine/tributary#90]
tributary does `import graphviz`, not `import pygraphviz`, so I think that:
  * in pip land you need to `pip install graphviz` and also make sure you have the actual graphviz installed (e.g. via your system package manager or whatever)
  * in conda land you need to `conda install python-graphviz` (which itself depends on `graphviz`).

The other package here is `pygraphviz`, which provides the python module `pygraphviz`. Although that's listed in the dependencies of tributary, I _think_ it's unused. Which is lucky, because the way pygraphviz is specified in setup.py (following on from the pandas dependency, which is missing its trailing comma), it doesn't get installed. Which is lucky, because `pip install pygraphviz` (and hence `pip install tributary`) would probably fail for most people anyway (unless their system is set up to build it) :)

**Comment by timkpaine** [comment]
https://github.com/timkpaine/tributary/issues/33
